name: Build CTAN and TDS archives

on:
  workflow_dispatch:
  workflow_run:
    workflows: 
      - "Run tests"
    types: 
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-sciffi
      
      - name: Build
        run: l3build ctan test-basic

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sciffi-build-${{ github.sha }}
          path: |
            build/distrib/ctan/
            build/distrib/tds/
            *.zip
          retention-days: 90
