name: Run tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-sciffi
      - uses: ./.github/actions/setup-python-bindings

      - name: lua tests
        run: l3build unittest

      - name: regression tests
        timeout-minutes: 10
        run: l3build check

      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-failures-${{ github.sha }}
          path: |
            build/test/*.diff
            build/test/*.log
          retention-days: 30
